version: '2'

services: 
  ms-helloworld:
    container_name: ms-helloworld
    user: root # avoids ton of volume mounting headaches in dev mode.
    build: .
    volumes:
      - .:/home/app
    ports:
      - 3737
    environment:
      - APP_ENV=development
    command: scripts/build.sh

# @see: https://github.com/pilu/fresh
# @alt @see: https://github.com/codegangsta/gin

